<?php

namespace Database\Seeders;

use App\Models\Cat;
use Illuminate\Database\Seeder;

class CatSeeder extends Seeder
{
    public function run(): void
    {
        $cats = [
            [
                'breed_id'       => 1,
                'name'           => 'Biscuit',
                'price'          => 5000000.00,
                'age_in_months'  => 4,
                'gender'         => 'male',
                'color'          => 'Blue Silver',
                'weight'         => 2.50,
                'description'    => 'Dễ thương, đã ăn được cơm',
                'health_status'  => 'Tốt',
                'is_vaccinated'  => true,
                'stock_status'   => 'available',
                'link_image'     => 'https://cdn.eva.vn/upload/3-2022/images/2022-08-26/image2-1661495595-733-width1920height1874.jpg',
            ],
            [
                'breed_id'       => 1,
                'name'           => 'Cookie',
                'price'          => 5200000.00,
                'age_in_months'  => 3,
                'gender'         => 'female',
                'color'          => 'British Blue',
                'weight'         => 2.10,
                'description'    => 'Mẹ là冠军, giấy tờ đầy đủ',
                'health_status'  => 'Xuất sắc',
                'is_vaccinated'  => true,
                'stock_status'   => 'available',
                'link_image'     => 'https://azpet.com.vn/wp-content/uploads/2021/07/meo-ba-tu-1-1024x768.jpg',
            ],
            [
                'breed_id'       => 1,
                'name'           => 'Mochi',
                'price'          => 4800000.00,
                'age_in_months'  => 5,
                'gender'         => 'male',
                'color'          => 'Colorpoint',
                'weight'         => 3.00,
                'description'    => 'Tính tình siêu lười',
                'health_status'  => 'Tốt',
                'is_vaccinated'  => true,
                'stock_status'   => 'reserved',
                'link_image'     => 'https://tropicpet.vn/wp-content/uploads/2025/02/meo-ba-tu-2.jpg',
            ],
            [
                'breed_id'       => 2,
                'name'           => 'Dumbo',
                'price'          => 6500000.00,
                'age_in_months'  => 2,
                'gender'         => 'male',
                'color'          => 'White',
                'weight'         => 1.80,
                'description'    => 'Tai gấp siêu gấu, mắt to tròn',
                'health_status'  => 'Tốt',
                'is_vaccinated'  => false,
                'stock_status'   => 'available',
                'link_image'     => 'https://cdn.tgdd.vn/Files/2021/04/23/1345712/meo-tai-cup-scottish-fold-nguon-goc-dac-diem-gia-ban-202203291550131830.jpg',
            ],
            [
                'breed_id'       => 2,
                'name'           => 'Luna',
                'price'          => 6800000.00,
                'age_in_months'  => 3,
                'gender'         => 'female',
                'color'          => 'Fawn',
                'weight'         => 2.00,
                'description'    => 'Tai gấp pure, giấy tờ đầy đủ',
                'health_status'  => 'Tốt',
                'is_vaccinated'  => true,
                'stock_status'   => 'available',
                'link_image'     => 'https://cdn.tgdd.vn/Files/2021/04/23/1345712/nguon-goc-dac-diem-cach-nuoi-bang-gia-cua-meo-tai-cup-scottish-fold-202104231412164258.jpg',
            ],
            [
                'breed_id'       => 3,
                'name'           => 'Simba',
                'price'          => 8000000.00,
                'age_in_months'  => 4,
                'gender'         => 'male',
                'color'          => 'Golden',
                'weight'         => 3.50,
                'description'    => 'Bộ lông cực đẹp, mặt doll',
                'health_status'  => 'Tốt',
                'is_vaccinated'  => true,
                'stock_status'   => 'available',
                'link_image'     => 'https://cdn.eva.vn/upload/3-2022/images/2022-08-26/image7-1661495595-967-width1180height800.jpg',
            ],
            [
                'breed_id'       => 3,
                'name'           => 'Nala',
                'price'          => 7500000.00,
                'age_in_months'  => 5,
                'gender'         => 'female',
                'color'          => 'White',
                'weight'         => 3.20,
                'description'    => 'Lông trắng muốt, cần chăm sóc lông kỹ',
                'health_status'  => 'Tốt',
                'is_vaccinated'  => true,
                'stock_status'   => 'sold',
                'link_image'     => 'https://lolipet.net/wp-content/uploads/Persian-Cat.jpg',
            ],
            [
                'breed_id'       => 4,
                'name'           => 'Leo',
                'price'          => 12000000.00,
                'age_in_months'  => 3,
                'gender'         => 'male',
                'color'          => 'Tabby',
                'weight'         => 4.00,
                'description'    => 'Tiềm năng to lớn',
                'health_status'  => 'Xuất sắc',
                'is_vaccinated'  => true,
                'stock_status'   => 'available',
                'link_image'     => 'https://cdn.hstatic.net/files/200000945871/article/meo-maine-coon_b8aa37bc893240af923cf388e848bdfa.jpg',
            ],
            [
                'breed_id'       => 4,
                'name'           => 'Daisy',
                'price'          => 11500000.00,
                'age_in_months'  => 4,
                'gender'         => 'female',
                'color'          => 'Black Silver',
                'weight'         => 3.80,
                'description'    => 'Đẹp như tiểu thư',
                'health_status'  => 'Tốt',
                'is_vaccinated'  => true,
                'stock_status'   => 'available',
                'link_image'     => 'https://petnow.com.vn/wp-content/uploads/2025/07/z6813132549632_0f30ce6c1c064d0836ea4aa450bcb2ed.jpg',
            ],
            [
                'breed_id'       => 5,
                'name'           => 'Angel',
                'price'          => 9500000.00,
                'age_in_months'  => 3,
                'gender'         => 'female',
                'color'          => 'Seal Point',
                'weight'         => 2.80,
                'description'    => 'Mắt xanh biếc, xả rồ hoàn toàn',
                'health_status'  => 'Tốt',
                'is_vaccinated'  => true,
                'stock_status'   => 'available',
                'link_image'     => 'https://peticon.edu.vn/wp-content/uploads/2023/10/meo_ragdoll2.jpeg',
            ],
            [
                'breed_id'       => 5,
                'name'           => 'Oliver',
                'price'          => 10000000.00,
                'age_in_months'  => 4,
                'gender'         => 'male',
                'color'          => 'Blue Bicolor',
                'weight'         => 3.50,
                'description'    => 'Bờm sư tử đẹp trai',
                'health_status'  => 'Tốt',
                'is_vaccinated'  => true,
                'stock_status'   => 'available',
                'link_image'     => 'https://pethouse.com.vn/wp-content/uploads/2025/12/meo-ragdoll-dep-ma-RD4193-1247x1496.jpg',
            ],
            [
                'breed_id'       => 6,
                'name'           => 'Simba Jr',
                'price'          => 15000000.00,
                'age_in_months'  => 2,
                'gender'         => 'male',
                'color'          => 'Brown Rosetted',
                'weight'         => 2.00,
                'description'    => 'Họa tiết báo rừng rõ nét',
                'health_status'  => 'Xuất sắc',
                'is_vaccinated'  => true,
                'stock_status'   => 'available',
                'link_image'     => 'https://petcorner.vn/wp-content/uploads/2025/05/Dac-diem-meo-Bengal.jpg',
            ],
            [
                'breed_id'       => 7,
                'name'           => 'Yoda',
                'price'          => 11000000.00,
                'age_in_months'  => 5,
                'gender'         => 'male',
                'color'          => 'Pink',
                'weight'         => 3.50,
                'description'    => 'Không lông, tính người cực kỳ',
                'health_status'  => 'Tốt',
                'is_vaccinated'  => true,
                'stock_status'   => 'available',
                'link_image'     => 'https://petcorner.vn/wp-content/uploads/2025/05/Cach-cham-soc-meo-Ai-Cap-o-Viet-Nam.jpg',
            ],
            [
                'breed_id'       => 8,
                'name'           => 'Misty',
                'price'          => 7000000.00,
                'age_in_months'  => 3,
                'gender'         => 'female',
                'color'          => 'Grey Silver',
                'weight'         => 2.20,
                'description'    => 'Sợ người lạ nhưng rất trung thành',
                'health_status'  => 'Tốt',
                'is_vaccinated'  => true,
                'stock_status'   => 'available',
                'link_image'     => 'https://nuoitrong.com/wp-content/uploads/2023/12/meo-russian-blue-6.jpg',
            ],
            [
                'breed_id'       => 9,
                'name'           => 'Tom',
                'price'          => 5500000.00,
                'age_in_months'  => 4,
                'gender'         => 'male',
                'color'          => 'Silver Tabby',
                'weight'         => 4.00,
                'description'    => 'Sức khỏe siêu phàm, ít bệnh',
                'health_status'  => 'Xuất sắc',
                'is_vaccinated'  => true,
                'stock_status'   => 'available',
                'link_image'     => 'https://peticon.edu.vn/wp-content/uploads/2024/05/bi-quyet-nuoi-meo-my-long-ngan.jpeg',
            ],
            [
                'breed_id'       => 10,
                'name'           => 'Luna',
                'price'          => 4000000.00,
                'age_in_months'  => 3,
                'gender'         => 'female',
                'color'          => 'Seal Point',
                'weight'         => 2.50,
                'description'    => 'Thích nói chuyện, rất nhõ',
                'health_status'  => 'Tốt',
                'is_vaccinated'  => true,
                'stock_status'   => 'available',
                'link_image'     => 'https://cdn.tgdd.vn/Files/2021/04/23/1345745/dac-diem-gia-va-cach-nuoi-meo-meo-xiem-siamese-cat-202203301447406105.jpg',
            ],
        ];

        foreach ($cats as $cat) {
            Cat::create($cat);
        }
    }
}
